# Generated by Django 4.1.1 on 2022-11-16 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0008_contact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='status',
            field=models.IntegerField(choices=[(0, 'Active'), (1, 'Done')], default=0),
        ),
    ]
